apache:
  image: apache
  links:
    - mariadb:mariadb
  ports:
    - 80:80
    - 9001:9001
  volumes:
    - ./../symfony-pull-list:/var/www/html


mariadb:
  image: mariadb
  ports:
    - 3306:3306
  #volumes:
  #  - ./../mariadb-data:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: rootpassword

