apache:
  image: apache
  links:
    - mariadb:mariadb
  ports:
    - 80:80
  volumes:
    - ./../pull-list-symfony:/var/www/html

mariadb:
  image: mariadb
  ports:
    - 3306:3306
  environment:
    MYSQL_ROOT_PASSWORD: rootpassword


phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
    - mariadb:mariadb
  ports:
    - 8181:80
  environment:
    MYSQL_ROOT_PASSWORD: rootpassword
    PMA_PORT: 3306